# Generated by Django 3.1.3 on 2021-01-10 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=100)),
                ('message', models.CharField(choices=[('Skin', 'Skin Care Treatment'), ('Body', 'Body Treatment'), ('Weight', 'Weight Management')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'APPOINTMENTS',
            },
        ),
    ]
