# Generated by Django 3.1.3 on 2021-01-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210119_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='message',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
