# Generated by Django 3.1.3 on 2021-01-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210119_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='postal',
        ),
    ]
