# Generated by Django 3.1.3 on 2021-01-20 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_appointments_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
